[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "discord-s3"
dynamic = ["version"]
description = "S3 storage with Discord"
readme = "README.md"
requires-python = ">=3.14.7"
license = "MIT"
authors = [
    {name = "Fabio Antonio Astore", email = "astore.a.fabio@gmail.com"}
]
dependencies = []

[tool.hatch.version]
path = "src/discord_s3/__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/discord_s3"]

[tool.hatch.build.targets.sdist]
packages = ["src/discord_s3"]
